class DefaultQuotes {
  static const List<String> quotes = [
    "I will wake up and seize the day",
    "Discipline equals freedom",
    "The early bird catches the worm",
    "Rise and shine, the world awaits",
    "Success is the sum of small efforts repeated",
    "Wake up with determination, go to bed with satisfaction",
    "Every morning is a blank canvas, paint it well",
    "Don't let your dreams just be dreams",
    "Today is another chance to get it right",
    "Your future is created by what you do today",
    "The secret of getting ahead is getting started",
    "Dream big, work hard, stay focused",
    "Believe you can and you're halfway there",
    "Great things never came from comfort zones",
    "Do something today that your future self will thank you for",
    "If it doesn't challenge you, it won't change you",
    "Focus on your goals, not your obstacles",
    "The best time to start was yesterday, the next best time is now",
    "Make today your masterpiece",
    "It always seems impossible until it is done",
    "You don't have to be great to start, but you have to start to be great",
    "Hard work beats talent when talent doesn't work hard",
    "A year from now you will wish you had started today",
    "Motivation gets you going, habit keeps you going",
    "Success doesn't just find you, you have to go out and get it",
    "Push yourself, because no one else is going to do it for you",
    "Don't stop when you're tired, stop when you're done",
    "The harder you work for something, the greater you'll feel when you achieve it",
    "Wake up, smile and tell yourself today is my day",
    "Every morning starts a new page in your story, make it a great one",
    "Opportunities don't happen, you create them",
    "Success is not final, failure is not fatal, it is the courage to continue that counts",
    "I am in charge of how I feel and today I am choosing happiness",
    "No matter how you feel, get up, dress up and show up",
    "Some people dream of success, while others wake up and work for it",
    "The only bad workout is the one that didn't happen",
    "What you do today can improve all your tomorrows",
    "I am stronger than my excuses",
    "Don't count the days, make the days count",
    "The only limit to our realization of tomorrow will be our doubts of today",
    "Strive for progress, not perfection",
    "Don't wait for opportunity, create it",
    "Small steps in the right direction can turn out to be the biggest step of your life",
    "Believe in yourself and all that you are",
    "Success is what happens after you have survived all your disappointments",
    "You are never too old to set another goal or to dream a new dream",
    "Keep your eyes on the stars, and your feet on the ground",
    "The future belongs to those who believe in the beauty of their dreams",
    "Fall seven times and stand up eight",
    "Yesterday is not ours to recover, but tomorrow is ours to win or lose"
  ];
}
